package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* jueves 5 de noviembre de 2015 20H05' COT
*/

public interface CalculadoraOperations 
{
  double add (double x, double y);
  double substract (double x, double y);
  double multiply (double x, double y);
  void shutdown ();
} // interface CalculadoraOperations
