package CalculadoraApp;


/**
* CalculadoraApp/Calculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* jueves 5 de noviembre de 2015 20H05' COT
*/

public interface Calculadora extends CalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculadora
